name: Node.js CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: check out git repo
        uses: actions/checkout@v3
        with:
          lfs: true
      - run: git lfs pull

      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Cache circom
        id: cache-circom
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/circom
          key: ${{ runner.os }}-circom

      - name: Install circom
        if: steps.cache-circom.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/iden3/circom.git
          cd circom
          cargo build --release
          cargo install --path circom
          circom --help

      - name: Cache yarn install
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: |
          yarn install

      - name: Build circuits and contracts
        run: |
          yarn build

      - name: Compile Typescript
        run: |
          yarn tsc

      - name: Test
        run: |
          yarn test
